### ISSUE TITLE
Allow the user to navigate between compatible articles in the reader

### ISSUE THREAD

**Issue by sleepyfran** [sleepyfran/readder#15]
Right now we load multiple posts that are compatible with the user's filters but we only show one and we don't allow the user to navigate between them. We should add arrows on the edges of the screen to take the user one article forward or backward in the compatible articles list.

**Comment by danielharvilik** [comment]
@sleepyfran 
Hey, is this available?

**Comment by sleepyfran** [comment]
Sure thing, @danielharvilik 😀

**Comment by danielharvilik** [comment]
Is there anything to know specificly about code ?
Or guide which file should be changed?

**Comment by sleepyfran** [comment]
Not really, I'd recommend to just take a look around at how things are organised and try to follow the same patterns. Of course if you have any doubt you can ask here and I'll try my best to explain it. There's no guide at the moment either, I'd recommend you to take care of another issue that might be a little bit more friendly for newcomers like #14 and after you become a little bit more familiar with the code you can tackle this one :)

**Comment by danielharvilik** [comment]
Allright thanks for replying, #14 What that issue really mean?
