### ISSUE TITLE
Notify errors and empty results to the user

### ISSUE THREAD

**Issue by sleepyfran** [sleepyfran/readder#2]
The _Home_ view should start reacting to other states than success. Right now, whenever we get a response from the API, we always navigate to the Reader page; however, there are certain cases in which the community that the user wrote does not exist (the API should call onError and set the loadingStatus of the store to _error_) or none of the fetched post can be read in the specified time (the API should call onNoResults and set the loadingStatus of the store to _noResults_). We should handle these scenarios and notify the user about these cases.

We can start by proposing how to show these error messages in the UI.

**Comment by peoray** [comment]
I'd like to work on this. Although, I need additional info

**Comment by sleepyfran** [comment]
>I'd like to work on this. Although, I need additional info

@peoray great! I’ll update the description with more information as soon as I can!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sleepyfran** [comment]
@peoray I updated the issue for more details, tell me if you need any additional info!

**Comment by peoray** [comment]
I'll start working on this issue, I expect to run into bugs :), so stick around!
