### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by peoray** [sleepyfran/readder#9]
Hi

Saw this as a comment on dev.to and decided to check here. Would love to go over the application and contribute in any way I can.

Great work already

**Comment by sleepyfran** [comment]
Hey! Glad to see that you want to contribute 😄 

You can take a look at the opened issues or add your own if you see something missing. You can take a look at #2 (needs some UI proposals) or #7.

I'm closing this issue, but feel free to comment any doubt you have in here!
